spring:
  datasource:
    url: jdbc:mysql:///1903_shop2
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://47.112.137.117:2181
  protocol:
    name: dubbo
    port: -1
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml