spring:
  datasource:
    url: jdbc:mysql:///1903_shop2
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://47.112.137.117:2181
  protocol:
    port: -1
    name: dubbo
  consumer:
    check: false
    timeout: 10000
    retries: 3
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml